# Generated by Django 2.2.3 on 2019-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_details', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('deposit_amt', models.FloatField()),
                ('widhdraw_amt', models.TextField()),
            ],
        ),
    ]
