# Generated by Django 2.2.3 on 2019-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='acc_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
