# Generated by Django 2.2.3 on 2019-07-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_fraud_acc_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraud',
            old_name='widhdraw_amt',
            new_name='withdraw_amt',
        ),
    ]
