# Generated by Django 2.2.3 on 2019-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_auto_20190715_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud',
            name='subset_size',
            field=models.IntegerField(default=0),
        ),
    ]
